Integrate 0x DAO
boardroom-inc/protocol-Info pull request #445
Opened 2021-11-20 18:37 UTC by cryptosabago

2021-11-27 18:59 UTC, Rashmi-278 commented on protocols/0x/index.json
> +  "cname": "0x",
Hey sandra, could you please change the cname to 0xgov ? 
It would be better if it's more than three characters

2021-11-27 19:00 UTC, Rashmi-278 requested changes
cname and path needs to be changed to 0xgov

2021-12-03 20:16 UTC, Rashmi-278 requested changes
Hey sandra, the changes look good ! 
There a few more additions needed. 
0xgov seems to have discourse and snapshot for their governance
can you please fill in the details of it too ? 

according to this https://docs.boardroom.info/adding-your-project/adding-your-project/protocol-information

here are links 
https://snapshot.org/#/0xgov.eth/
https://gov.0x.org/

2021-12-03 21:21 UTC, cryptosabago commented
> https://gov.0x.org/

@Rashmi-278 
I searched high and low for this discourse link, I thought it would be under the domain: `discourse.org\SOMEDAO`. So I figured that they had nothing with discourse.
How does one find info about a DAO in general? 
I struggled in particular with the discourse, and the overview in general. 
Thanks

2021-12-05 15:09 UTC, Rashmi-278 commented
> @Rashmi-278 I searched high and low for this discourse link, I thought it would be under the domain: `discourse.org\SOMEDAO`. So I figured that they had nothing with discourse. How does one find info about a DAO in general? I struggled in particular with the discourse, and the overview in general. Thanks

Hey , the info is usually on the main website , if we don't find it we track their social media for links or updates and in general google for em.

Can you update the details of discourse links in PR ?

2021-12-05 15:10 UTC, Rashmi-278 commented
And for category we visit the discourse forun and click on the governance category then in URL look for the number

for this it's https://gov.0x.org/c/governance/13

2021-12-11 20:35 UTC, cryptosabago commented
@Rashmi-278 Thanks again for the help. Did I miss anything this time?

2021-12-12 07:29 UTC, Rashmi-278 submitted a review, later dismissed

2021-12-12 08:49 UTC, Rashmi-278 commented
> @Rashmi-278 Thanks again for the help. Did I miss anything this time?

Hey ! One last thing, we recently updated the docx so the discourse links format is changed.

```
discourseForum: {
  url: "",
  categoryId: "" 
}
```

2021-12-18 19:44 UTC, Rashmi-278 approved these changes

2021-12-19 13:32 UTC, merged