Yung Ape Dao first commit
boardroom-inc/protocol-Info pull request #486
Opened 2022-01-02 14:15 UTC by thedeini

2022-01-04 18:13 UTC, Rashmi-278 requested changes

2022-01-04 18:41 UTC, thedeini commented on protocols/yungapedao/index.json
> +  "cname": "Yung Ape Dao",
Wow, I messed up big time on my second commit but fixed it right after, can you check and verify if everything is alright? Or should I open another PR? Sorry for this problem...

2022-01-05 17:44 UTC, Rashmi-278 requested changes

2022-01-05 17:44 UTC, Rashmi-278 commented on protocols/yungapedao/index.json
> +  "cname": "YungApeDao",
please change all the letters to small , this is an parameter to retrieve protocols and will not displayed.

2022-01-05 17:44 UTC, Rashmi-278 commented on protocols/yungapedao/index.json
> +  "cname": "YungApeDao",
please make it all smallcase, this parameter is not used for display, we use it to retrieve protocols

2022-01-05 17:45 UTC, Rashmi-278 commented on protocols/yungapedao/index.json
> +  "cname": "Yung Ape Dao",
No worries, we can keep this PR :)

2022-01-06 12:15 UTC, thedeini commented on protocols/yungapedao/index.json
> +  "cname": "Yung Ape Dao",
Thanks for that :)

2022-01-09 15:57 UTC, Rashmi-278 submitted a review, later dismissed

2022-01-09 19:13 UTC, Rashmi-278 commented
Closing this as new PR will be added focusing only on the relevant changes to files with logo addition.

2022-01-09 19:13 UTC, closed without merging