Add CityDAO protocol info
boardroom-inc/protocol-Info pull request #488
Opened 2022-01-10 14:02 UTC by cryptosabago

2022-01-10 14:11 UTC, cryptosabago commented
@Rashmi-278 do you have any idea how i can fix the `yarn run` error? Not sure if it is related to my recent OS upgrade...

2022-01-10 15:08 UTC, CarlGocht commented
> @Rashmi-278 do you have any idea how i can fix the `yarn run` error? Not sure if it is related to my recent OS upgrade...

Sorry about that I think it was my fault. Can you rebase on main and try again

2022-01-10 19:33 UTC, Rashmi-278 requested changes

2022-01-10 19:33 UTC, Rashmi-278 commented on protocols/cityDAO/index.json
> +  "cname": "CityDAO",
All small case please :)

2022-01-10 19:33 UTC, Rashmi-278 commented on protocols/cityDAO/index.json
> +  "path": "CityDAO",
All small case :)

2022-01-10 19:33 UTC, Rashmi-278 commented on protocols/cityDAO/index.json
> +    "url": "https://forum.citydao.io/c/cips/",
Please remove /c/cips/

2022-01-10 19:33 UTC, Rashmi-278 commented on protocols/cityDAO/index.json
> +    "url": "https://forum.citydao.io/c/cips/",
Just https://forum.citydao.io/

2022-01-12 15:27 UTC, Rashmi-278 approved these changes

2022-01-20 12:41 UTC, merged