Add moloch dao
boardroom-inc/protocol-Info pull request #498
Opened 2022-01-29 16:31 UTC by cryptosabago

2022-01-30 17:54 UTC, Rashmi-278 requested changes

2022-01-30 17:54 UTC, Rashmi-278 commented on protocols/molochdao/index.json
> +  "type": "moloch",
@CarlGocht @sudheerDev  , Would type 'moloch' cause problem ?

2022-01-31 06:52 UTC, Rashmi-278 approved these changes

2022-02-01 15:11 UTC, Rashmi-278 requested changes
Add logo image for moloch dao's if they are not found on coingecko.
For this, add molochrises/logo.png 

Also please change directory name to molochrises

2022-02-03 10:20 UTC, sudheerDev approved these changes

2022-02-03 10:22 UTC, merged